apiVersion: v1
kind: PersistentVolume
metadata:
  name: dropit-webroot
  labels:
    type: local
#  annotations:
#    pv.beta.kubernetes.io/gid: "webfiles"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/dropit0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dropit-claim-webroot
  labels:
    app: dropit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi