apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        track: stable
    spec:
      containers:
        - name: nginx
          image: puraskar/nginx:1.0.5
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          ports:
          - containerPort: 8080
