apiVersion: v1
kind: Service
metadata:
  name: dropit-server-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
    nodePort: 30001

  selector:
    app: dropit
  type: NodePort